# Custom config
app:
  mongodb:
    host: localhost
    port: 27017
    user: user
    password: pass
    database: catalog-command-db
  kafka:
    group:
      paidOrders: paid-orders-group
      ordersWaitingValidation: orders-waiting-validation-group

spring:
  application:
    name: catalog-command
  data:
    # Mongo
    mongodb:
      host: ${app.mongodb.host}
      port: ${app.mongodb.port}
      username: ${app.mongodb.user}
      password: ${app.mongodb.password}
      database: ${app.mongodb.database}
      authentication-database: admin
  # Kafka
  kafka:
    producer:
      transaction-id-prefix: tx-catalog-
    consumer:
      enable-auto-commit: false

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    enabled: false
  kafka:
    clientid: catalog-command-app
    producer:
      retries: 3
      bootstrap-servers: ${app.kafka.broker.host}:${app.kafka.broker.port}
      event-processor-mode: tracking
    properties:
      security.protocol: PLAINTEXT

# Metrics
management:
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server:
          requests: true
      slo:
        http:
          server:
            requests: 50ms, 100ms, 200ms, 400ms
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99, 0.999

---
spring:
  config:
    activate:
      on-profile: docker

app:
  mongodb:
    host: mongo
    user: ${MONGO_USER}
    password: ${MONGO_PASSWORD} # TODO use cipher
